spring:
  profiles:
    active: dev

---

spring:
  security:
    user:
      password: disabled # evitar login default
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://postgres:5432/ecommerce
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
jwt:
  secret: super-secreta-para-jwt-nao-expirar
  expiration: 86400000 # 1 dia em ms

data:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  redis:
    host: redis
    port: 6379

  kafka:
    bootstrap-servers: kafka:9092

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080
